# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
    lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :firebase do
  build

  firebase_app_distribution(
      app: "1:928660756997:android:52358ec27e400ced42da6c",
      groups: "group2",
      release_notes: "Lots of amazing new features to test out!"
  )
end

  desc "Deploy a new beta version to the Google Play"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(track: 'beta')
  end
end
