name: delayed-dispatched-workflow
on:
  workflow_dispatch:
    inputs:
      attemptNumber:
        description: 'Attempt number'
        required: false
        default: '1'
      maxAttempts:
        description: 'Max attempts'
        required: false
        default: '5'
jobs:
  doTheRestOfTheWork:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
        # - name: Get the next attempt number
        #   id: getNextAttemptNumber
        #   uses: cardinalby/js-eval-action@v1
        #   env:
        #     attemptNumber: ${{ github.event.inputs.attemptNumber }}
        #     maxAttempts: ${{ github.event.inputs.maxAttempts }}
        #   with:
        #     expression: |
        #       {
        #         const
        #           attempt = parseInt(env.attemptNumber),
        #           max = parseInt(env.maxAttempts);
        #         assert(attempt && max && max >= attempt);
        #         return attempt < max ? attempt + 1 : '';
        #       }
        # - name: Fake work
        #   id: actualWorkStep
        #   continue-on-error: true
        #   ## Call itself again
        #   uses: benc-uk/workflow-dispatch@v1
        #   ## If actualWorkStep failed and maxAttempts hasn't
        #   ## been reached
        #   if: |
        #     steps.actualWorkStep.outcome != 'success' &&
        #     steps.getNextAttemptNumber.outputs.result
        #   with:
        #     ## Pass the name of this workflow
        #     workflow: learn-github-actions
        #     token: ${{ secrets.PERSONAL_TOKEN }}
        #     ## Pass increased attemptNumber and current maxAttemptssdf
        #     inputs: |
        #       {
        #         "attemptNumber":
        #             "${{steps.getNextAttemptNumber.outputs.result}}",
        #         "maxAttempts":
        #             "${{github.event.inputs.maxAttempts}}"
        #       }
